config/routes.rb
Rails.application.routes.draw do

  get 'checklists/mytestchecklist'

  get 'taches/index'

  get 'taches/show'

  get 'taches/new'

  get 'checklists/en_cours'

  get 'checklists/en_cours_par_garant'

  get 'checklists/en_cours_par_createur'

  get 'checklists/terminees'

  get 'main/index'

  root 'checklists#en_cours'

    resources :checklists  do 
        get 'start'
        post 'finish' 
        get 'test'
        get 'nom_garant'
        resources :tasks do
          post 'update_status'
        end
        get 'new_tasks'     
    end

if false

     
  namespace :api, defaults: {format: :json}  do
    resources :checklists  do 
        get 'start'
        post 'finish' 
        resources :tasks
        get 'new_tasks'     
    end
  end
  

end

end

app/models/checklist.rb
require 'json'

class Checklist < ActiveRecord::Base
	has_many :tasks, dependent: :destroy
	accepts_nested_attributes_for :tasks, :reject_if => lambda { |b| b[:description].blank? }
	if false
			# attr_accessible :tasks_attributes
	end

	validates :title, uniqueness: true, presence: true, length: {minimum: 5 }

    def self.create_instance(template, garant)
        checklist = Checklist.new({ 
        title: template.title + ' - V' + template.template_version.to_s ,
    	description: template.description,
    	created_at: template.created_at,
    	updated_at: template.updated_at,
    	status: template.status,
    	progess: 1,
    	garant: garant,
    	timeStarted: DateTime.now.to_formatted_s(:long_ordinal),
    	timeFinished: template.timeFinished,
    	createur: template.createur,
        template_version: template.template_version
        })

        template.tasks.each do |task|
            checklist.tasks.new({
                description: task.description,
                status: false,
                created_at: task.created_at,
                updated_at: task.updated_at
                })
        end
        checklist.save
        template.template_version = template.template_version + 1
        template.save
        print "\n" 
        print "\n" 
        print "\n" 
        print "\n" 
        print "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    	print checklist.to_json

    	checklist
    end
	
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController

	def index
		@checklists = Checklist.all.order('checklists."updated_at" desc','checklists.created_at desc')

	end


	def new
		@checklist = Checklist.new
		@task = Task.new
		# @checklist.tasks.build
  		#@task = @checklist.tasks.new(task_params)
		
	end

	def new_tasks
	    @checklist = Checklist.find(params[:checklist_id]) 
	    5.times { @checklist.tasks.build }	
	    @tasks = Task.all
    end 


    def nom_garant
	    @checklist = Checklist.find(params[:checklist_id]) 
    end


	def en_cours
		@checklists = Checklist.all.order('checklists."timeStarted" desc','checklists.created_at asc')
	end

	def en_cours_par_garant
		@checklists = Checklist.all.order('checklists."garant" desc','checklists."timeStarted" desc')
	end

	def en_cours_par_createur
		@checklists = Checklist.all.order('checklists."createur" desc','checklists."timeStarted" desc')
	end

	def terminees
		@checklists = Checklist.all.order('checklists."timeFinished" desc','checklists."timeStarted" desc')
	end

	def demaree
		@checklists = Checklist.all.order('checklists."timeStarted" desc','checklists.created_at asc')
	end

	def show
		@checklist = Checklist.find(params[:id]) 
		@tasks = Task.all
		case @checklist.progess
	    when 0
			render 'show_unstarted.html.erb'
		when 1
			render 'show_started.html.erb'
		when 2
			render 'show_started.html.erb'
		else
			render 'show.html.erb'
		end
	end

	def mychecklist
		@checklist = Checklist.find(params[:checklist_id])
	end

	def start
		@checklist = Checklist.find(params[:checklist_id])	
		# @checklist.timeStarted = DateTime.now.to_formatted_s(:long_ordinal)
		# @checklist.timeStarted
		# @checklist.save
		# @checklist.progess = '1' 
		# @checklist.save
		# @progress = @checklist.progess.to_i
        

		print '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Version :' 
		print @checklist.template_version

		# smell strange with garant
		@checklist_copie = Checklist.create_instance(@checklist, @checklist.garant)
		@checklist_copie.save  	


#		@checklist_copie = @checklist.clone

#		@checklist_copie.id = nil
#		@checklist_copie.timeStarted = DateTime.now.to_formatted_s(:long_ordinal)
#		@checklist_copie.timeStarted
#		@checklist_copie.progess = '1' 
#		@checklist_copie.save
#		@progress_copie = @checklist_copie.progess.to_i

		 redirect_to checklist_path(@checklist_copie)

		# redirect_to checklist_path(@checklist)
	end

	def create
		@checklist = Checklist.new(checklist_params)


		if @checklist.save
			@checklist.progess = '0'
			#verifier quae ca amrhce ! 
			@checklist.template_version = 1
			@checklist.save
			@progress = @checklist.progess.to_i		
			redirect_to checklist_path(@checklist)

		else
			render 'new'
		end
	end

	def update
		@checklist = Checklist.find(params[:id])
		print checklist_params;
		if @checklist.update(checklist_params)
			@checklist.save
			redirect_to checklist_start_path(@checklist)
		else
			render 'edit'
		end
	end


	def destroy
		@checklist = Checklist.find(params[:id])
		@checklist.destroy

		if @checklist.progess == 0 
			redirect_to checklists_path
		elsif @checklist.progess == 1
			redirect_to checklists_en_cours_path
		elsif @checklist.progess == 2
			redirect_to checklists_terminees_path
		end

	end



    def finish
    	#TODO: Implement method and update button label
    	@checklist = Checklist.find(params[:checklist_id])
    	@checklist.timeFinished = DateTime.now.to_formatted_s(:long_ordinal) 
    	@checklist.save
    	@checklist.progess = '2' 
    	@checklist.save
		@progress = @checklist.progess.to_i
    	redirect_to checklist_path(@checklist)
    end


	private
	def checklist_params
		params.require(:checklist).permit(:title, :description, :status, :createur, :garant)
	end

end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/index.html.erb
<div class="container">
	<div class= "col-md-8 col-md-offset-2 top30">
		<div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
						<li><a href="/main/index">Home</a></li>
						<li class="active"><a href="/checklists">Modèles</a></li>
				</ol>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class= "col-md-12 col-md-offset-2">
	<% n =0 %>
	<div class="row new-checklist-row">
		<div class="col-md-2 created-row top30"><!-- Column create -->
			<div class="row top30">
				<div class="empty-template top30">
					<p>
						<center><%= link_to image_tag("plus.png", size: "30x30"), new_checklist_path %></center>
					</p>	
				</div>

			</div>
			<div class="row">
				<div class="empty-template-text">
					<p>
						<center><%= link_to 'Créer ton modèle', new_checklist_path %></center>
					</p>	
				</div>
				
			</div>			
		</div>
		<div class="col-md-6 template-row"><!-- Column templates -->
			<div class="page-header">
				<h1>Tout les modèles</h1>
			</div>
			<div class="row template-checklist-row">


			<table class="table table-striped table-condensed">
				    <thead>
				        <tr>
				            <th>Titre</th>
				            <th>Description</th>			           
							<th>Créateur</th>
				            <th></th>
				        </tr>
				    </thead>
				    <tbody>
				    	<% @checklists.each do |checklist| %>
				    		<% if checklist.progess == 0 %>   <!-- if checklist started -->
						        <tr>
						            <td><%=link_to checklist.title, checklist_path(checklist) %></td>
						            <td>
						            	<% if checklist.description.blank? %>
											Pas de description <br>
										<% else %>
											<%= checklist.description %><br>
										<% end %>
						            </td>
						            <td>
						            	<% if !(checklist.createur.blank?) %>
											<h6 id="createur" font-size:"1"><%= checklist.createur %></h6>
										<% else %>
											Pas de nom
										<% end %>
									</td>
						            <td><%= link_to image_tag("delete.png", size: "15x15"), checklist_path(checklist),
							              method: :delete,
							             data: { confirm: 'Etes vous sûr?' } %></td>
						        </tr>
					        <% end %>
				    	<% end %>
				    </tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/checklists/mytestchecklist.html.erb
<div class="container">
<h1> Checklist du nouvel arrivant </h1>
<br><br>
	<div>
		1. Checklist hard codée<br> 
		2. Checklist peut être consultée<br>
		3. Pivotal tracker mis à jour<br>
		4. User story vérifiée<br>
		5. Dernière tâche<br>
	</div>
</div>

app/views/checklists/new_tasks.html.erb
<div class="container">
	<div class= "col-md-8 col-md-offset-2 top30 ">
		<div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
						<li><a href="/main/index">Home</a></li>
						<% if @checklist.progess == 1 %>
							<li class="active"><a href="/checklists/en_cours">En cours</a></li>
						<% elsif @checklist.progess == 2 %>
							<li class="active"><a href="/checklists/terminees">Terminées</a></li>
						<% end %>
						<li class="active"><%= @checklist.title.titleize %></li>
				</ol>
			</div>
		</div>
	</div>
</div>



<% if true %>




<div class="container ">
	<div class="checklist-details">
		<div class="row">
			<div class= "col-md-8 col-md-offset-2 ">
				<div class="row">
					<div class="col-md-12">	
						<h1 class="page-header">
							<%= @checklist.title.titleize %>
						</h1>	
						<div class="btn-toolbar pull-right bottom30">
							<p>
							 	<% if !(@checklist.createur.blank?) %>
									Crée par <%= @checklist.createur.capitalize%>
								<% end %>
							</p>
							<p>
								<% if !(@checklist.garant.blank?) %>
									Démarée par <%= @checklist.garant.capitalize %>
								<% end %>
							</p>
						</div>
						<p class="lead">
							<%= @checklist.description.capitalize %>
						</p>
					</div>
				</div>
				<div class="row">
						<% if @checklist.tasks.count == 0 %>    
							<p>
						    	Pas de tâches 
						    </p>
						<% elsif  @checklist.tasks.count > 0 %> 
								<% n =0 %>
								<% @checklist.tasks.order("created_at desc").each do |task| %>
										<div class="input-group input-group-lg">
												<span class="input-group-addon"><%= link_to image_tag("delete.png", size: "15x15"), checklist_task_path(@checklist, task),
								              method: :delete,
								             data: { confirm: 'Etes vous sûr?' } %></span>
								             <% if @checklist.progess == 1 %>
												<span class="input-group-addon checklist-details-task">
									 				<%= check_box_tag task.status, unchecked_value = !(task.status), checked_value = task.status, checklist: @checklist.id, taskid: task.id %>
									 			</span>
									 			<% if task.status == false %>
													<input type="text" class="form-control task" placeholder='<%= task.description.capitalize %>' disabled="disabled">
												<% elsif task.status == true %>
													<input type="text" class="form-control task" placeholder='<%= task.description.capitalize %>' disabled="disabled">
												<% end %>
											<% elsif @checklist.progess == 2 %>
								             	<span class="input-group-addon"><%= link_to image_tag("check.png", size: "15x15"), checklist_path(@checklist)%></span>
								             	<input type="text" class="form-control task" placeholder="<%= task.description.capitalize %>" disabled="disabled">
								            <% end %>
				  								
										</div>
							 	<% end %>

						<% end %> 	

				<div class="row">
					<div class="display-add top30">
						<p>
							<% if @checklist.progess == 1 %>
									<%= render 'tasks/form' %>
							<% elsif @checklist.progess == 2 %>
								<h2>Objectif atteint</h2>
							<% end %>
						</p>
					</div>
				</div>
						<div class="btn-toolbar pull-right top30" role="toolbar">
					    	<div class="btn-group">
					    		<%= link_to ' Supprimer', checklist_path(@checklist), 
					    		method: :delete, data: { confirm: 'Are you sure?' },
					    		:class =>"btn btn-danger glyphicon glyphicon-trash", 
					    		:type => "button",
					    		:style => "height:34px" %>
					      </div>
					    </div>	


					    <div class="row">
					<div class="display-save bottom30">
						<% if @checklist.progess == 1 %>
							<p>
								<% if @checklist.tasks.count > 0 %>
									<p>
										<button type="button" class="btn btn-default btn-lg glyphicon glyphicon-ok">
											<%= link_to "J'ai réalisé toutes les tâches", checklist_finish_path(@checklist), data: {confirm: 'La checklist est términée. Vous ne pourrez plus la modifier.'} %>
										</button>
									</p>
								<% elsif @checklist.tasks.count == 0 && !(@checklist.description.blank?) %>
									<p>
										<%= link_to "J'ai suivi la description", :class => 'btn btn-default btn-lg', data: {confirm: 'La checklist est términée. Vous ne pourrez plus la modifier.'} do %>
    											J'ai suivi la description <span class="glyphicon glyphicon-ok" ></span>
										<% end %>
									</p>
								<% end %>
							</p>
						<% end %>
					</div>
				</div>

						
					</div>				
				</div> <!-- row -->
			</div>
		</div>		
	</div>
</div>
	
<% end %> <!-- end of if true/false -->

app/views/checklists/show.html.erb
<h1>Checklist : <%= @checklist.title %></h1> 

	<% if @checklist.progess == 0 %>
		<%= image_tag "start.png", size: "40x40"  %>
	<% elsif @checklist.progess == 1 %>
		<%= image_tag "inProgress.png", size: "40x40"  %>
	<% elsif @checklist.progess == 2 %>
		<%= image_tag "ObjectifAtteinds.jpeg", size: "40x40"  %>
	<% end %>

	<br><br>
		
		

<% if @checklist.tasks.count == 0 && @checklist.description.blank? %>    
    
    No tasks and no description 

<% elsif  @checklist.tasks.count == 0 && !(@checklist.description.blank?) %> 
	Description : <%= @checklist.description %><br>
	
<% elsif  @checklist.tasks.count > 0 && !(@checklist.description.blank?) %> 
<% n =0 %>
	Description : <%= @checklist.description %><br><br>
	Tache :   <br><br> 

	 	<% @checklist.tasks.each do |tache| %>
 		<%= n= n+1 %>. 
 		<%= tache.description %><br>
 		
 	<% end %>


  <% elsif @checklist.tasks.count > 0 && @checklist.description.blank? %>    
  Tache :   <br><br> 
  <% n = 0 %>
 	<% @checklist.tasks.each do |tache| %>
 	<!-- 	<%= check_box("taches", "new" )	%> -->
 		
 		<%= n= n+1 %>. 
 		<%= tache.description %><br>
 	<% end %>
 <% end %>


<br><br>

<% if @checklist.progess == 0 %>
	<%= render 'tasks/form' %>
	<%= link_to "Démarrer", checklist_start_path(@checklist) %><br>


<% elsif @checklist.progess == 1 %>
	<%= link_to "Add taches", checklist_new_tasks_path(@checklist) %>
<% elsif @checklist.progess == 2 %>
	<h2>Objectif atteint</h2>
<% end %>
		

app/views/checklists/show_started.html.erb
<div class="container">
	<div class= "col-md-8 col-md-offset-2 top30 ">
		<div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
						<li><a href="/main/index">Home</a></li>
						<% if @checklist.progess == 1 %>
							<li class="active"><a href="/checklists/en_cours">En cours</a></li>
						<% elsif @checklist.progess == 2 %>
							<li class="active"><a href="/checklists/terminees">Terminées</a></li>
						<% end %>
						<li class="active"><%= @checklist.title.titleize %></li>
				</ol>
			</div>
		</div>
	</div>
</div>


<% if true %>




<div class="container ">
	<div class="checklist-details">
		<div class="row">
			<div class= "col-md-8 col-md-offset-2 ">
				<div class="row">
					<div class="col-md-12">	
						<h1 class="page-header">
							<%= @checklist.title.titleize %>
						</h1>	
						<div class="btn-toolbar pull-right bottom30">
							<p>
							 	<% if !(@checklist.createur.blank?) %>
									Crée par <%= @checklist.createur.capitalize%>
								<% end %>
							</p>
							<p>
								<% if !(@checklist.garant.blank?) %>
									Démarée par <%= @checklist.garant.capitalize %>
								<% end %>
							</p>
						</div>
						<p class="lead">
							<%= @checklist.description.capitalize %>
						</p>
					</div>
				</div>
				<div class="row">
						<% if @checklist.tasks.count == 0 %>    
							<p>
						    	Pas de tâches
						    </p>
						<% elsif  @checklist.tasks.count > 0 %> 
								<% n =0 %>
								<% @checklist.tasks.order("created_at desc").each do |task| %>
										<div class="input-group input-group-lg">
												<span class="input-group-addon"><%= link_to image_tag("delete.png", size: "15x15"), checklist_task_path(@checklist, task),
								              method: :delete,
								             data: { confirm: 'Etes vous sûr?' } %></span>
								             <% if @checklist.progess == 1 %>
												<span class="input-group-addon checklist-details-task">
									 				<%= check_box_tag task.status, unchecked_value = !(task.status), checked_value = task.status, checklist: @checklist.id, taskid: task.id %>
									 			</span>
									 			<% if task.status == false %>
													<input type="text" class="form-control task" placeholder='<%= task.description.capitalize %>' disabled="disabled">
												<% elsif task.status == true %>
													<input type="text" class="form-control task" placeholder='<%= task.description.capitalize %>' disabled="disabled">
												<% end %>
											<% elsif @checklist.progess == 2 %>
								             	<span class="input-group-addon"><%= link_to image_tag("check.png", size: "15x15"), checklist_path(@checklist)%></span>
								             	<input type="text" class="form-control task" placeholder="<%= task.description %>" disabled="disabled">
								            <% end %>
				  								
										</div>
							 	<% end %>

						<% end %> 	

				<div class="row">
					<div class="display-add top30">
						<p>
							<% if @checklist.progess == 1 %>
								<a href="#"><span class="glyphicon glyphicon-plus"></span></a>
								<%= link_to "Ajouter une tâche", checklist_new_tasks_path(@checklist) %>
							<% elsif @checklist.progess == 2 %>
								<h2>Objectif atteint</h2>
							<% end %>
						</p>
					</div>
				</div>

						<div class="btn-toolbar pull-right top30" role="toolbar">
					    	<div class="btn-group">
					    		<%= link_to ' Supprimer', checklist_path(@checklist), 
					    		method: :delete, data: { confirm: 'Are you sure?' },
					    		:class =>"btn btn-danger glyphicon glyphicon-trash", 
					    		:type => "button",
					    		:style => "height:34px" %>
					      </div>
					    </div>	


					    <div class="row">
					<div class="display-save bottom30">
						<% if @checklist.progess == 1 %>
							<p>
								<% if @checklist.tasks.count > 0 %>
									<p>
										<button type="button" class="btn btn-default btn-lg glyphicon glyphicon-ok">
											<%= link_to "J'ai réalisé toutes les tâches", checklist_finish_path(@checklist), method: 'post' , data: {confirm: 'La checklist est términée. Vous ne pourrez plus la modifier.'}%>
										</button>
									</p>
								<% elsif @checklist.tasks.count == 0 && !(@checklist.description.blank?) %>
	<p>
										<button type="button" class="btn btn-default btn-lg glyphicon glyphicon-ok">
											<%= link_to "J'ai suivi la description", checklist_finish_path(@checklist), method: 'post' , data: {confirm: 'La checklist est términée. Vous ne pourrez plus la modifier.'}%>
										</button>
									</p>
								<% end %>
							</p>
						<% end %>
					</div>
				</div>

						
					</div>				
				</div> <!-- row -->
			</div>
		</div>		
	</div>
</div>
	
<% end %> <!-- end of if true/false -->



<% if false %> 
<div class="container">
	<div class= "col-md-10 col-md-offset-2">
		<div class="row">
	<!-- 		<div class="col-md-2 description-info ">
				<div class="row">
					<div class="actual-description">
						<% if !(@checklist.description.blank?) %>
							Description : <%= @checklist.description %>
						<% elsif @checklist.description.blank? %>
							No description of checklist
						<% end %>
					</div>
				</div>
				<div class="row">
					<div class="author-name">
						<p>
							<% if  !(@checklist.garant.blank?) %>
								<font size ="2px">Démarrée par : </font><%= @checklist.garant %>
							<% else %>
								Le garant n'a pas donné son nom
							<% end %>
						</p>
						<p>
							<% if !(@checklist.createur.blank?) %>
								<font size ="2px">Créee par : </font><%= @checklist.createur %>
							<% else %>
								Le créateur n'a pas donné son nom
							<% end %>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="icons-display">
						<div class="icons col-xs-12">
	      <a href="#"><span class="glyphicon glyphicon-trash"></span></a>
							<a href="#"><span class="glyphicon glyphicon-edit"></span></a>
					    </div>
					</div>
				</div>						
			</div> -->
			<div class= "col-md-9 col-md-offset-1 display">
				<div class="row">
					<h1 class="page-header">
							<%= @checklist.title.titleize %>
						</h1>	
						<div class="btn-toolbar pull-right">
							Crée par <%= @checklist.createur.capitalize %>
						</div>
						<p class="lead">
							<%= @checklist.description.capitalize %>
						</p>
				</div>
				<div class="row top30">
					<div class="tasks-display">
						<% if @checklist.tasks.count == 0 %>    
							<p>
						    	No tasks 
						    </p>
						<% elsif  @checklist.tasks.count > 0 %> 
							<ul class="list-group">
								<% n = 0 %>
								<% @checklist.tasks.order("created_at asc").each do |task| %>
									<li class="checklist-details-task">
										<span class="task-status"><% task.status %></span>
										<label class="category-select">
											<% if @checklist.progess == 2 %>
												<%= n = n +1 %>.
											<% else %> 
								 				<%= check_box_tag task.status, unchecked_value = !(task.status), checked_value = task.status, checklist: @checklist.id, taskid: task.id %>
								 			<% end %>
								 			<% if task.status == true %>
								 				<strike><%= task.description %></strike>
								 				<%= link_to image_tag("delete.png", size: "15x15"), checklist_task_path(@checklist, task),
							              method: :delete,
							             data: { confirm: 'Are you sure?' } %>
								 			<% else %>
								 				<%= label_tag task.description %>
								 				<%= link_to image_tag("delete.png", size: "15x15"), checklist_task_path(@checklist, task),
							              method: :delete,
							             data: { confirm: 'Are you sure?' } %>
								 			<% end %>
							 			</label>
									</li>
							 	<% end %>
							</ul>
						<% end %> <!-- end of if condition -->
					</div><!-- task display-->
				</div> <!-- row -->
				<div class="row">
					<div class="display-add">
						<p>
							<% if @checklist.progess == 1 %>
								<a href="#"><span class="glyphicon glyphicon-plus"></span></a>
								<%= link_to "Add tasks", checklist_new_tasks_path(@checklist) %>
							<% elsif @checklist.progess == 2 %>
								<h2>Objectif atteint</h2>
							<% end %>
						</p>
					</div>
				</div>
				<div class="row"> 
					<div class="display-save">
						<% if @checklist.progess == 1 %>
							<p>
								<% if @checklist.tasks.count > 0 %>
									<p>
										<%= button_to "J'ai réalisé toutes les tâches", checklist_finish_path(@checklist), data: {confirm: 'La checklist est términée. Vous ne pourrez plus la modifier.'} %> 
									</p>
								<% elsif @checklist.tasks.count == 0 && !(@checklist.description.blank?) %>
									<p>
										<%= button_to "J'ai suivi la description", checklist_finish_path(@checklist), data: {confirm: 'La checklist est términée. Vous ne pourrez plus la modifier.'} %> 
									</p>
								<% end %>
							</p>
						<% end %>
					</div>
				</div>			
			</div>
		</div>		
	</div>
</div>

<% end %> <!-- end of if true/false -->

app/views/checklists/show_unstarted.html.erb
<div class="container">
	<div class= "col-md-8 col-md-offset-2 top30">
		<div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
						<li><a href="/main/index">Home</a></li>
						<li><a href="/checklists">Modèles</a></li>
  						<li class="active"><%= @checklist.title.titleize %></li>
				</ol>
			</div>
		</div>
	</div>
</div>


<% if true %>

<div class="container ">
	<div class="checklist-details ">
		<div class="row">
			<div class= "col-md-8 col-md-offset-2 ">
				<div class="row">
					<div class="col-md-12">	
						<h1 class="page-header">
							<%= @checklist.title.titleize %>
						</h1>
						<% if !(@checklist.createur.blank?) %>
							<div class="btn-toolbar pull-right">
								Crée par <%= @checklist.createur.capitalize %>
							</div>
						<% else %>
							<div class="btn-toolbar pull-right">
								Le créateur n'a pas donné son nom
							</div>
						<% end %>
						<p class="lead">
							<%= @checklist.description.capitalize %>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="bottom30 top30">
							<%= render 'tasks/form' %>
						</div>

						<% if @checklist.tasks.count == 0 %>    
							<p>
						    	Pas de tâches 
						    </p>
						<% elsif  @checklist.tasks.count > 0 %> 


								<% n =0 %>
								<% @checklist.tasks.order("created_at desc").each do |task| %>
									<div class="input-group input-group-lg">
											<span class="input-group-addon"><%= link_to image_tag("delete.png", size: "15x15"), checklist_task_path(@checklist, task),
							              method: :delete,
							             data: { confirm: 'Are you sure?' } %></span>
											<span class="input-group-addon"><span class="glyphicon glyphicon-ok"></span></span>	
			  								<input type="text" class="form-control task" placeholder='<%= task.description.capitalize %>' disabled="disabled">
									</div>
							 	<% end %>
						<% end %> 	

						<div class="btn-toolbar pull-right top30 bottom30" role="toolbar">
					    	<div class="btn-group">
					    		<%= link_to ' Supprimer', checklist_path(@checklist), 
					    		method: :delete, data: { confirm: 'Etes vous sûr?' },
					    		:class =>"btn btn-danger glyphicon glyphicon-trash", 
					    		:type => "button",
					    		:style => "height:34px" %>
					    		<%= link_to ' Démarrer', checklist_nom_garant_path(@checklist), 
					    		:class =>"btn btn-success glyphicon glyphicon-ok", 
					    		:type => "button",
					    		:style => "height:34px" %>
					      </div>
					    </div>					
						
					</div>				
				</div> <!-- row -->

			</div>
		</div>		
	</div>
</div>
	
<% end %> <!-- end of if true/false -->