config/routes.rb
Rails.application.routes.draw do

  get 'checklists/mytestchecklist'

  get 'taches/index'

  get 'taches/show'

  get 'taches/new'

  get 'checklists/en_cours'

  get 'checklists/en_cours_par_garant'

  get 'checklists/en_cours_par_createur'

  get 'checklists/terminees'

  get 'main/index'

  root 'checklists#en_cours'

    resources :checklists  do 
        get 'start'
        post 'finish' 
        get 'test'
        get 'nom_garant'
        resources :tasks do
          post 'update_status'
        end
        get 'new_tasks'     
    end

if false

     
  namespace :api, defaults: {format: :json}  do
    resources :checklists  do 
        get 'start'
        post 'finish' 
        resources :tasks
        get 'new_tasks'     
    end
  end
  

end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheckIT</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js" %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular-resource.min.js" %>
  <%= javascript_include_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" %> 

</head>
<body>



<nav class="navbar navbar-inverse" role="navigation">
      <div class="container ">
        <div class="row">
          <div class= "col-md-8 col-md-offset-2 ">
            <div class="navbar-header">
              <a href="/" class="navbar-brand">CheckIT</a>
            </div>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                  <a class="dropdown-toggle active" data-toggle="dropdown" href="/checklists/en_cours">
                    Checklists en Cours <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/checklists/en_cours">Checklists en Cours</a></li>
                    <li role="presentation" class="divider"></li>
                    <% Checklist.all.order('checklists."timeStarted" desc').each do |checklist|%>
                      <% if checklist.progess == 1 %>
                        <% if checklist.garant.blank? %>
                          <li role="presentation"><%= link_to checklist.title + ' - ' +  'Pas de garant' , checklist_path(checklist) %></li>
                        <% else %>
                          <li role="presentation"><%= link_to checklist.title + ' - ' + (checklist.garant) , checklist_path(checklist) %></li>
                        <% end %>
                      <% end %>
                    <% end %>
                  </ul>
                  
              </li>
              <li class="dropdown">
                  <a class="dropdown-toggle active" data-toggle="dropdown" href="/checklists/terminees">
                    Checklists Terminées <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/checklists/terminees">Checklists Terminées</a></li>
                    <li role="presentation" class="divider"></li>
                   <% Checklist.all.order('checklists."timeFinished" desc').each do |checklist|%>
                    <% if checklist.progess == 2 %>
                      <% if checklist.garant.blank? %>
                          <li role="presentation"><%= link_to checklist.title + ' - ' +  'Pas de garant' , checklist_path(checklist) %></li>
                        <% else %>
                          <li role="presentation"><%= link_to checklist.title + ' - ' + (checklist.garant) , checklist_path(checklist) %></li>
                        <% end %>
                      <% end %>
                    <% end %>
                  </ul>
              </li>  
               <li class="dropdown">
                  <a class="dropdown-toggle active" data-toggle="dropdown" href="/checklists/terminees">
                    Modèles <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/checklists/">Modèles</a></li>
                    <li role="presentation" class="divider"></li>
                   <% Checklist.all.each do |checklist|%>
                    <% if checklist.progess == 0 %>
                      <li role="presentation"><%= link_to checklist.title  , checklist_path(checklist) %></li>  
                      <% end %>
                    <% end %>
                  </ul>
              </li> 
              <li><a href="/checklists/new">Créer un Modèle</a></li>                                     
              </ul>
          </div>
          </div>
      </div>
</nav>


	<%= yield %>


</body>
</html>